### ISSUE TITLE
Add ability to centralize redundant markup

### ISSUE THREAD

**Issue by rspurgeon** [confluentinc/kafka-tutorials#113]
For example, the following files are duplicates, and have drift potential:
```
➜ find . -name "get-cp.adoc"
./_includes/tutorials/joining-stream-table/kstreams/markup/dev/get-cp.adoc
./_includes/tutorials/filtering/kstreams/markup/dev/get-cp.adoc
./_includes/tutorials/transforming/kafka/markup/dev/get-cp.adoc
./_includes/tutorials/transforming/kstreams/markup/dev/get-cp.adoc
./_includes/tutorials/tumbling-windows/kstreams/markup/dev/get-cp.adoc
./_includes/tutorials/splitting/kstreams/markup/dev/get-cp.adoc
./_includes/tutorials/merging/kstreams/markup/dev/get-cp.adoc
```
Each tutorial also requires idential 'steps' yaml stanzas:
```
  steps:
    - title: Get Confluent Platform
      content:
        - action: skip
          render:
            file: tutorials/filtering/kstreams/markup/dev/get-cp.adoc
```
