### ISSUE TITLE
Connect/KStreams: rename existing tutorial to differentiate from upcoming tutorial

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#219]
JDBC source connector does not add a key but most KStreams operations require a key.

The key can be added in one of two places:

* In Kafka Streams: captured by KT https://github.com/confluentinc/kafka-tutorials/issues/123 (done)
* In the Connect framework with an SMT: captured by KT https://github.com/confluentinc/kafka-tutorials/issues/122 (open)

However, the naming of the first tutorial (which is already done and live) is too broad and cannot be differentiated from the new tutorial.  It doesn't specify 

(a) where the key is added (KStreams vs Connect) 
(b) the format (SpecificAvro vs JSON)

This GH issue is to rename the existing tutorial to be more specific, to disambiguate from the other tutorial (and future tutorials)

Initial proposal:

* Rename the existing one at https://github.com/confluentinc/kafka-tutorials/issues/123 to `connect-jdbc-kstreams-rekey-specificavro`, with similar title
* Name the new one at https://github.com/confluentinc/kafka-tutorials/issues/122 to `connect-jdbc-rekey-smt-kstreams-json`, with similar title

**Comment by ybyzek** [comment]
From @bbejeck 

> connect-jdbc-<RE-KEY OPERATOR>-rekey-<SERIALIZED-TYPE>

Which would result in

* `connect-jdbc-kstreams-rekey-specificavro`
* `connect-jdbc-smt-rekey-kstreams-json`

**Comment by ybyzek** [comment]
Resolved

**Comment by ybyzek** [comment]
cc: @colinhicks 

In Kafka Streams: captured by KT #123 (done)

- connect-jdbc-kstreams-rekey-specificavro
- “Add a key to a stream from a JDBC source”

In the Connect framework with an SMT: captured by KT #122 (open)

- connect-jdbc-smt-rekey-kstreams-json
- “Key a topic from Kafka Connect with an SMT”

**Comment by rmoff** [comment]
I'm about to start on #122 now. My intention is for it to be a generic tutorial on setting the key in data written by a source connector (regardless of which connector, and which value format). 
So I propose 

* shortname: `connect-source-smt-set-key`
* SEO slug: `add-key-to-topic-with-kafka-connect-smt`
* Tutorial title: `Add a key to a stream from Kafka Connect`

**Comment by rmoff** [comment]
Looking at this further, I think we need consense whether what I am writing is the equivalent of what we have already. The existing tutorial is very specific in title as well as internal references to the source (JDBC). 

```
connect-jdbc-kstreams-rekey-specificavro:
  title: "Ingesting data via a JDBC source connector into Kafka Streams as SpecificAvro, adding a key in Kafka Streams"
  slug: "/connect-jdbc-kstreams-rekey-specificavro"
  problem: "you have data in a table in a database, are pulling that data via a JDBC source connector (which by default does not add a key to the Kafka message), and you want to create a Kafka Stream using SpecificAvro, letting Kafka Streams add the key."
  introduction: "Consider a database with a table with names of cities. The JDBC source connector can read that data into Kafka but, by default, the topic will not have keys. In Kafka Streams, ingest that data using SpecificAvro and add a key to the stream."
  status:
    ksql: disabled
    kstreams: enabled
``` 

So should we reframe the existing tutorial to make it generic in referencing to the Kafka Connect source, and then deploy this SMT one alongside it?
