### ISSUE TITLE
Provide smooth path for users to run Control Center Docker with any tutorial

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#460]
Control Center provides nice UI for users who want to:

* inspect topic data
* use ksqlDB UI instead of CLI

cc: @SrWaves

**Comment by ybyzek** [comment]
Manual workaround: before running the harness runner, add a file `docker-compose.override.yml` (with control center) to the subdirectory for the KT (same location as where the `docker-compose.yml` file is)

```
  control-center:
    image: confluentinc/cp-enterprise-control-center:5.5.0
    hostname: control-center
    container_name: control-center
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
```
